version: '3.4'

services:
  tinyurl:
    image: ${DOCKER_REGISTRY-}tinyurl
    build:
      context: .
      dockerfile: TinyUrl/Dockerfile   
    ports:
      - "5000:5000"
      - "5001:5001"

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: